version: "3.2"

services:

  php:
    build: ./docker/php
    volumes:
      - ./app:/var/www/
    environment:
      - "DB_HOST=pgsql"
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_PASSWORD=homestead"
      - "REDIS_HOST=redis"
      - "REDIS_PORT=6379"

  nginx:
    build: ./docker/nginx
    volumes:
      - ./docker/php
      - ./log/nginx:/var/log/nginx
    ports:
      - 80:80

  mydb:
    image: postgres
    volumes:
      - /var/lib/postgresql/data
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=homestead"
    ports:
      - "3306:3306"

volumes:
db-data:
driver: local
